FROM node:12.16.3-alpine as build
RUN mkdir /code
WORKDIR /code
ENV PATH /code/node_modules/.bin:$PATH
COPY package.json /code/package.json
RUN yarn install --silent
RUN yarn global add @vue/cli@4.4.1 -g
COPY . /code
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
ARG VUE_APP_API_SERVICE_URL
ENV VUE_APP_API_SERVICE_URL $VUE_APP_API_SERVICE_URL
ARG VUE_APP_AUTH0_DOMAIN
ENV VUE_APP_AUTH0_DOMAIN $VUE_APP_AUTH0_DOMAIN
ARG VUE_APP_AUTH0_AUDIENCE
ENV VUE_APP_AUTH0_AUDIENCE $VUE_APP_AUTH0_AUDIENCE
ARG VUE_APP_AUTH0_CLIENT_ID
ENV VUE_APP_AUTH0_CLIENT_ID $VUE_APP_AUTH0_CLIENT_ID
RUN yarn build

FROM nginx:1.15.9-alpine
COPY --from=build /code/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
